services:

  webserver:
    # Aby pliki byly poprawnie synchronizowane między kontenerem a windowsem
    volumes:
      - ./:/var/www/html/
      - vendor:/var/www/html/vendor
      - var:/var/www/html/var
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

volumes:
  vendor:
  var: